// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Leituras de sensor
//
//	Devolve leituras de sensor guardadas na base de dados
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.0.1
//
//	Consumes:
//	  - application/com.github.edyknopfler.apifirst.sensor-measurement.v1+json
//
//	Produces:
//	  - application/com.github.edyknopfler.apifirst.measurement-list.v1+json
//
// swagger:meta
package restapi
